#!/bin/bash

NAME="plurios-plymouth-theme-spinner"
VERSION="0.1"
ARCH="all"
DIR_PACKAGE="${NAME}_${VERSION}_${ARCH}"

rm -rf $NAME*
if ls *.deb >/dev/null 2>&1
then
  rm -f *.deb
fi

mkdir $DIR_PACKAGE
cp -r DEBIAN/ $DIR_PACKAGE/
cp -r usr $DIR_PACKAGE/

SIZE=$(du -ks  --exclude=DEBIAN $DIR_PACKAGE/ | awk '{print $1}')

sed -i "s/CHANGE_NAME/$NAME/g" $DIR_PACKAGE/DEBIAN/control
sed -i "s/CHANGE_VERSION/$VERSION/g" $DIR_PACKAGE/DEBIAN/control
sed -i "s/CHANGE_SIZE/$SIZE/g" $DIR_PACKAGE/DEBIAN/control

chmod 755 $DIR_PACKAGE/DEBIAN/{postinst,postrm,prerm}
chown -R root:root $DIR_PACKAGE/

dpkg-deb --build $DIR_PACKAGE/

